apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy-ingress-controller
  namespace: argocd
spec:
  destination:
    namespace: haproxy-controller
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize: {}
    path: haproxy-ingress-controller
    repoURL: https://github.com/thriqon/kubernetes-example-apps.git
